### ISSUE TITLE
require() not supported

### ISSUE THREAD

**Issue by aopt** [mbostock/ndjson-cli#45]
Using node v16.13.2 I get:

Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Users\erwin\AppData\Roaming\npm\node_modules\d3\src\index.js from C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\requires.js not supported.
Instead change the require of index.js in C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\requires.js to a dynamic import() which is available in all CommonJS modules.
    at module.exports (C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\requires.js:6:12)
    at Command.<anonymous> (C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\node_modules\commander\index.js:412:13)
    at Command.emit (node:events:390:28)
    at Command.parseOptions (C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\node_modules\commander\index.js:730:14)
    at Command.parse (C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\node_modules\commander\index.js:471:21)
    at Object.<anonymous> (C:\Users\erwin\AppData\Roaming\npm\node_modules\ndjson-cli\ndjson-map:15:6) {
  code: 'ERR_REQUIRE_ESM'
}

**Comment by mbostock** [comment]
[D3 7.0](https://github.com/d3/d3/releases/tag/v7.0.0) and above is released as an ES module, so you won’t be able to require it using this library. You’ll need to use D3 6.x or below in conjunction with `-r`.

The NDJSON CLI could (should) add support for importing ES modules rather than using CommonJS require, but I’m not actively maintaining this library, so don’t hold your breath. 🙂

**Comment by aopt** [comment]
Thanks. Using d3 6 helped me over the hump.
